### PR TITLE
Dwc mapping

### PR DESCRIPTION
**Pull request by LienReyserhove**
This PR contains an overview of the Darwin Core mapping terms of the [alien birds checklist](https://docs.google.com/spreadsheets/d/1ugsmAq_tlUjFmZef2zyw-mT0Tq1jSdPlNO4KTfJyXVo/edit#gid=0). Please tick off the boxes if the mapping terms is considered OK.

### Input data

see #2 

### Taxon core

- [x] language
- [x] license 
- [x] rightsHolder
- [x] accessRights 
- [x] datasetID
- [x] institutionCode
- [x] datasetName
- [x] taxonID
- [x] scientificName
- [x] kingdom
- [x] phylum
- [x] class
- [x] order
- [x] family
- [x] genus
- [x] taxonRank: see [issue 3](https://github.com/trias-project/alien-birds-checklist/issues/3)
- [x] nomenclaturalCode

### Distribution extension

- [x] locationID
- [x] locality
- [x] countryCode
- [x] occurrenceStatus
- [x] establishmentMeans
- [x] eventDate
- [x] source: see #6 
- [x] occurrenceRemarks: see #7 

### Species profile extension

- [x] isMarine: always FALSE
- [x] isTerrestrial: always TRUE
- [x] isFreshwater: ~~always FALSE~~

### Description extension

- [x] `type` = Native range
- [x] `type` = Pathways of introduction
- [x] `type` = Degree of establishment

### CODE REVIEW

**Review by peterdesmet — CHANGES_REQUESTED** [review]
- [x] I think it is the first time we use `degree of establishment`? Our paper suggests readable values like `native`, `cultivated`, `established`. I would stick to that rather than `Blackburn et al. 2011:reproducing (C2)`. Alternatively, we could use `blackburn_2011:c2_reproducing`
- [x] None of the birds is freshwater related? That seems incorrect for e.g. ducks.
- [x] Name `species_profile.csv` -> `speciesprofile.csv`
- [x] Use capital in `Brussels-Capital region` -> `Brussels-Capital Region`
- [x] Place `locationID` before `locality`
- [x] source: write `wnm.be` as `http://waarnemingen.be`. Also add `http` to observations.be
- [x] I would also map all higher classification: it's in the spreadsheet (and discussed in the metadata), so why not add it.

**Comment by LienReyserhove** [comment]
Thanks for the review!

With respect to some of the issues:
1. I deliberately used `degree of establishment` for the first time to make it match to the proposed changes in vocabularies by @qgroom. Another option (and in line with the WGSRPD vocabulary we use here) could be `established (blackburn_2012: C2)`

2. None of the birds in the [source checklist](https://docs.google.com/spreadsheets/d/1ugsmAq_tlUjFmZef2zyw-mT0Tq1jSdPlNO4KTfJyXVo/edit#gid=0) have a realm of `freshwater`. I considered this to be OK as for me, waterbirds are also terrestrial to a certain point. @timadriaens could you help in this discussion please?

**Comment by timadriaens** [comment]
OK, I see that in Harmonia all Anatidae are considered freshwater. It seems to me that it would be best to bring the checklist in line with this.

**Comment by peterdesmet** [comment]
`established (blackburn_2012:C2)` (no space) is ok for me.

**Comment by timadriaens** [comment]
I did this, and also for Alcedinidae, Ardeidae, Pelicanidae, Phalacrocoracidae, Rallidae, Ciconiidae. For some of the other waders (e.g. lapwings) it is less clear whether we should brand them freshwater.

**Comment by timadriaens** [comment]
@LienReyserhove perhaps good to include Cristina Preda of @DiederikStrubbe in these discussions

**Comment by timadriaens** [comment]
ok, for some of the families where it is less straigtfroward (ibisses, cranes) I have checked habitat at species level now

**Comment by timadriaens** [comment]
what to do with species like _Haliaeetus pelagicus_ which live along coasts, guess it would be strange to mark non-seabirds as marine, zo I left it at terrestrial for now...

**Comment by DiederikStrubbe** [comment]
I agree that the eagle should be terrestrial (despite it being a 'sea' eagle). Based on habitat descriptions from the HBW, it is clear that it is a terrestrial species that goes hunting at sea - not what I would call a truly 'marine' species.

HBW: Habitat: "Narrow strips of coast, together with forested valleys along lower reaches of rivers. Always nests near water containing fish, hence concentrated near mouths of rivers, or along sea coast; alternatively on rivers where salmon run, or by lakes, provided that they offer conditions necessary for the building of bulky nests. Most often river valleys, where almost all nests are built in trees. Also rocky coasts with terraced cliffs 100 m or more high. Nests also on cliffs far inland, and has been recorded to 1000 m. In a study with satellite-tracked individuals (n = 32), river habitats were mainly used in autumn, probably because of the availability of abundant post-spawn dead salmon; in winter about one third of eagles continued to be located on rivers, with others on sea coasts and lake sides; during the spring migration and breeding season habitat use by adult eagles probably reflected the variety of habitats in which breeding occurs, while sub-adults were located mainly on the sea coas"

**Comment by timadriaens** [comment]
ok, I followed the same reasoning, also with e.g. _Geronticus eremita_ a wader which nests on cliffs by the sea but is also mostly terrestrial

**Comment by LienReyserhove** [comment]
Ok, thanks @timadriaens and @DiederikStrubbe for your input. Can I consider the realm of the species to be OK now?

**Comment by LienReyserhove** [comment]
@peterdesmet ready for review!

**Comment by timadriaens** [comment]
yes, for me the habitat information is fine now

**Comment by peterdesmet** [comment]
Still one `observations.be` without `http` in `source` in distributions.

**Review by peterdesmet — CHANGES_REQUESTED** [review]
- [x] Remove the following fixed terms from the spreadsheet (and map as fixed terms): `kingdom`, `phylum`, `class`, `nomenclaturalCode`
- [x] Add `http` to one more `observations.be` in source
- [x] Fix #3

**Comment by LienReyserhove** [comment]
OK, changes integrated. I'm considering this PR as closed :-)

**Pull request merged**
